::: {.breadcrumbs}
* [Resources](resources.html)
* Travis Deployment 
:::

# Travis CI deployment

It can be handy to have code run when commits are pushed to GitHub - you can do lots of things with this, but commonly it is used to run unit tests, build a docker images, or deploy something. In this example we will deploy this website to github pages using Travis-CI (which is free for open repositories).

## Step by step

I'm not going to cover using the Travis GUI and enabling Travis for your Github account here - if you visit the website it should guide you through the step to turn it on for a repository. It is worth noting that https://travis-ci.org/ if for open repositories, the paid version is available at `.com`.  The rest of this guide assumes that you've activated Travis for your personal account or organisation.

### 1. Choose a language

Travis will run based on instructions stored in a `.travis.yml` file. See [their docs](https://docs.travis-ci.com/user/languages/r/) for more info. We specify that we're using `R` and that we want to cache packages.
 > Caching the packages will speed up the build as install times on Linux (which Travis uses) are very slow (reduction from 30mins to 3 mins for this build).

```yml
language: r

# cache packages so that each build doesn't require installation...
cache:
    packages: true
# Install packages we need
```

### 2. Generate an SSH key

Each time we push or pull from GitHub we're goign to use a ssh key generated just for this repo. Don't use your personal ssh key. To do so, use the command below, and make a note of where you save the key. 

```sh
ssh-keygen -t rsa -b 4096 -C "will@bowdit.ch"
>Generating public/private rsa key pair.
>Enter file in which to save the key (/Users/will.bowditch/.ssh/id_rsa): />Users/will.bowditch/projects/rap-website/deploy_key
```

### 3. Encrypt the key

We don't want to store the key in the repo, so we use travis to encrypt it (you'll need to install the `travis` command line tool).  This command is going to give us a command to add to our `.travis.yml` file. You can do this automatically by adding `--add`.

```sh
travis encrypt-file deploy_key
>encrypting deploy_key for ukgovdatascience/rap-website
>storing result as deploy_key.enc
>DANGER ZONE: Override existing deploy_key.enc? |no| yes
>storing secure env variables for decryption
>Please add the following to your build script(before_install stage in your >.travis.yml, for instance):
>    openssl aes-256-cbc -K $encrypted_516b420c1ae6_key-iv $encrypted_516b420c1ae6_iv -in deploy_key.enc-out deploy_key -d
>Pro Tip: You can add it automatically by running with--add.
>Make sure to add deploy_key.enc to the git repository.
>Make sure not to add deploy_key to the git repository.
>Commit all changes to your .travis.yml.
```
> Note I called the key generated earlier `deploy_key` and stored it in the repo. We dont want to commit this to the repository so best to add it to .gitignore or deleted it (you can always generate another one).


### 4. Tell Travis to decrypt the key

We need to add the `openssl` command to the `.travis.yml` file. This command is going to use two environment variables stored by travis to decrypt the ssh key.
```yml
# Decrypt the deployment key, used to push the result to the  repo
before_install:
    - openssl aes-256-cbc -K $encrypted_516b420c1ae6_key-iv    $encrypted_516b420c1ae6_iv -in deploy_key.enc-out deploy_key -d
```

### 5. Add the key to GitHub

Next we want to add the ssh key to the repository as a deployment key. You can find on GitHub by navigating to the `Repo > Settings > Deploy keys > Add deploy key`. There, paste in the public key you generated earlier.

> on OS X you can use`cat deploy_key.pub | pbcopy` 

Make sure you tick **allow write access** if you want the key to have permission to push to the repo, by default deploy keys are read only.
 
### 6. Now for the task

Finally, we are going to tell travis what scripts to run on each commit. To allow them to run they need to be made executable with `chmod +x`. What's in these scripts is arbitrary, but here we're going to build the book using rmarkdown and push it to a branch on github, only when it's on the master branch.

>Travis has a number of environment variables we can use to make scripts run only on pull requests or when on certain branches (see: https://docs.travis-ci.com/user/environment-variables/). Below we are only going to run the deploy script if it isn't a pull request and we're on the master branch. You can either put this in the yml or in the bash scripts (see `_deploy.sh`). 

```yml
# Make bash scripts executable, so they can be run later. 
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh

script:
- "./_build.sh"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_deploy.sh; else echo "PR so
not deploying"; fi
```

## Example Scripts

`_build.sh`:
```sh
#!/bin/bash

# Build the site in `/site`
Rscript -e "rmarkdown::render_site(input='site')"
```

`_deploy.sh`:
```sh
#!/bin/bash

# Start ssh agent and add key
eval "$(ssh-agent -s)" # Start the ssh agent
chmod 600 deploy_key
ssh-add deploy_key


# Only publish to gh-pages if on the master branch
if [[ $TRAVIS_BRANCH == 'master' ]]
then
  # configure your name and email if you have not done so
  git config --global user.email "your@email.com"
  git config --global user.name "your_github_username"

  # clone the repository to the book-output directory
  git clone -b gh-pages \
    git@github.com:ukgovdatascience/rap-website.git \
    book-output

  cd book-output
  
  # Remove everything from this branch.
  git rm -rf *
  
  # Copy the new site, add all, and commit!
  cp -r ../site/docs/* ./
  git add --all *
  git commit -m "Travis built book"
  git push -q origin gh-pages
else
  echo "Not publishing as not in MASTER branch"
fi
```