::: {.breadcrumbs}
* [Resources](resources.html)
* Coffee and coding
:::

# Coffee and coding

The aim of the Coffee & Coding meetups is to nurture, enable and encourage a
vibrant, supportive and inclusive coding community at an organisation. Coffee &
Coding provides a regular opportunity for people within an organisation who are
interested in coding to share skills and knowledge, provide advice and guidance
to each other and generally network and get to know each other.

A common format is 40 minutes for a presentation and questions to the
presenter/s followed by 20 minutes Code Surgery. The presentations usually take
the form of a demonstration of a tool or technique and/or a show and tell of
work done within the department using these methods.  The Code Surgery provides
the opportunity for people to pose any coding related queries/ruminations/ideas
to the gathered coding community.

Some sessions are live-streamed and recorded.  Contact presenters or organisers
for material (videos, slides, notes) that isn't publicly available -- it might
be possible for them to share it with you directly.

Offers to present sessions in other deparments are often gratefully accepted.

Table: Coffee and coding groups

| Organisation | Resources | Contact | Notes |
|--------------|-----------|---------|-------|
| Cabinet Office | [Website](https://co-analysis.github.io/co-coffee-and-coding/) and [GitHub](https://github.com/co-analysis/co-coffee-and-coding) | coffee-and-coding@cabinetoffice.gov.uk | Every two weeks on Fridays from 10.15 to 11.15, Horseguard's Parade and Google Hangouts |
| Department for Business, Energy and Industrial Strategy | `W:/TRAINSHARE` on CBAS (open only to CBAS users in BEIS and partner orgs) | coffeeandcoding@beis.gov.uk | Weekly at 10-11am on Wednesdays, open to all |
| Department for Education | https://github.com/dfe-analytical-services/coffee-and-coding | coffee.coding@education.gov.uk | Sessions are usually held on every other Wednesday morning from 10-11AM. Rooms are booked for the London, Sheffield, and Darlington offices. |
| Department of Health and Social Care | | https://www.eventbrite.co.uk/e/health-r-coding-club-tickets-52481515626 | All events are arranged via the eventbrite link. |
| Department for Transport | https://github.com/departmentfortransport/coffee-and-coding | coffee.coding@dft.gov.uk |  |
| Ministry of Defence | Internal GitLab | Charlie Willis charles.wills106@mod.uk | Usually once a month on Friday mornings |
| Ministry of Housing Communities and Local Government | Internal Microsoft Teams site 'Coffee & Coding Public' | coffeeandcoding@communities.gov.uk | Roughly fortnightly on Monday afternoon's, held in 2 Marsham Street, London |
| Ministry of Justice (MoJ) | https://github.com/moj-analytical-services/coffee-and-coding-public | Coffee-and-Coding@justice.gov.uk |  |
| Office for National Statistics Data Science Campus | https://github.com/datasciencecampus/coffee-and-coding | coffee.coding@ons.gov.uk | Monthly |
